FROM registry.access.redhat.com/ubi9/go-toolset

WORKDIR /var/tmp

COPY go.mod go.mod 
COPY main.go main.go
COPY go.sum go.sum
COPY key.pem key.pem
COPY cert.pem cert.pem

RUN go build 

COPY . .

CMD ["./qe-proxy"]
